# Generated by Django 5.2.3 on 2025-10-22 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_study_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
