# Generated by Django 5.2.3 on 2025-10-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
